os: linux
# Travis CI template for cfsd

language: cpp

sudo: required

branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"

services:
- docker

addons:
  apt:
    update: true

env:
  global:
  - BRANCH = ${TRAVIS_BRANCH}
  - DOCKERHUB='chalmersfsd'
  # shell syntax #*/ means remove the first slash and string before it, for example, "cfsd/opendlv" would become "opendlv"
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  # run the following in terminal to encrypt the username and passward
  #   travis encrypt DOCKER_USER=sechalmersfsd --add
  #   travis encrypt DOCKER_PASS=cfsdlynx --add

install:
- docker build -f Dockerfile.amd64 -t ${IMAGE}:${BRANCH} .

script: skip

after_success:
- if [[ -z "${TRAVIS_TAG}" ]]; then echo "This commit hasn't been tagged, will not be pushed to dockerhub"; exit 0; fi
- docker --version
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker tag ${IMAGE}:${BRANCH} ${DOCKERHUB}/${IMAGE}:${TAG}
- docker push ${DOCKERHUB}/${IMAGE}:${TAG}
- echo "${DOCKERHUB}/${IMAGE}:${TAG}"

notifications:
  email:
    on_success: never
    on_failure: never
