os: linux
# Travis CI template for cfsd

language: cpp

sudo: required

branches:
  only:
  - "/^test.*$/"
  - "/^v.*$/"

services:
- docker

addons:
  apt:
    update: false

env:
  global:
  - BRANCH = ${TRAVIS_BRANCH}
  # - DOCKERHUB='chalmersfsd'
  # shell syntax #*/ means remove the first slash and string before it, for example, "cfsd/opendlv" would become "opendlv"
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`

install:
- docker --version

script:
#- docker build -f Dockerfile.amd64 -t ${IMAGE}:${BRANCH} .
- echo "This is test branch"

after_success:
- echo "build number" ${TRAVIS_BUILD_NUMBER}
- echo "job number" ${TRAVIS_JOB_NUMBER}
# - docker tag ${IMAGE}:${BRANCH} ${DOCKERHUB}/${IMAGE}:${TAG}
# - docker push ${DOCKERHUB}/${IMAGE}:${TAG}
# - echo "${DOCKERHUB}/${IMAGE}:${TAG}"
# - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ -z "${TRAVIS_BRANCH}" ]]; then echo "not branch"; elif [[ -z "${TRAVIS_TAG}" ]]; then echo "not tag"; fi

notifications:
  email:
    on_success: never
    on_failure: never
