os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: false
env:
  global:
  - BRANCH = ${TRAVIS_BRANCH}
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: dzIRXxxVMGklHgjMprSkTtcX2ZkIwFMef9j2SRF0Qv3T1a2x4EfME1+YF8FHIXomoJ3cWxnDUIadF3HFcP76/oDLfr787Atf2nB7O/fE8XLUk/Dey8jl4VLQ/TFfXodhDCEw2I4iKyEhkG52qY2gDgJb9qbkaZnW+dhPewv6Pn3HqGGkRiA63yza6+rxqnWb4QlfJugvB036bNLS3+uw9fOeNqs5BMxN79H4Wk8avyxvI8ORgV86rbZf8U2qZflVRAH5frdB7kilykPq3jpMVQZ9e2YbT9oS1kq8PnF+6mTTE8tVX9VrLmfW+wB+3SsQdcehayZKytRvApfp6l9NVFuJG7StfLJoLoAKFLuPiyl6pzl4XseNrnw+xDTd6bAYa9DGzSZn3S8Mj+bIaUDraSQMWU0m2hAwbGhqBz3uRT7ydeH4TkAWFFw/+VzlylFCdBIZf3mEMMbQei/vc3m0Mv1sx4j+GoSipgDa2rzutOn1QvyJEqkopltgGaeL5MVfMnjs/XyOhA2DOFBU6KtgK7G1xtHxVqEVoV+AC9z35nsYd0RFIorayQLQF6FZIdfBYCMWYhWV3owB4WwCquFzaZpKOxlemSNM/zII3XflT1T0ToHfMFhSmMKjPW32EKgEcwE/5ANFsEmk2l7GIsWSprq98oneJMVOcFJHCRJYSn4=
  - secure: C/m3zWvLvm3HrOnMKrB+Ty2e76E/bsrYwzEAiK+MOKlghJUuGvean/sINc1h9ayYmC/u0ct4A76Crxh7GNZgUJcF3u/kPyMdEbVyAnFdqNrZHJlVe17/oMKmbPGYVBes2qaKIvWnAtiCVAJ+YSc6OOwM1X+v7rADC+8Lps4ZYNhcTu6xHpO0Uzy3WmJiBUk1lTxqmhD6VnHyDRu0PjyaevLL1BpLy4ABmJ0jahE6Zw32PIQie1yW1xrpKuS+Hk4PS2E7RKVDVEP0q/7jylx9ALDNLV3ZIu3YQ+MzQ5rRRn1Xmoi2e/HnQadeR1Fbz5P2x9PYLjE0aNsIr2OwokZNWc3I8ZgVce/4swcFbZu9g5b30/vL6lT72QcogVkH53yBoZQAEKbayPJveMEk6IoIRBw9698zZ8GXnsw7p/CRQyTMaZyegRxTCTEnLGbSiNsJtE3IT87qcZ//alLLaHEhwAJUflzexwBDHuMijWNr2PzWM0hABxGyAqg6Ab3Qg7TiEMpCtTUkjU5i/tr4ACP7+2sR9zv8tG2SZZADhie342Hl0lka35MrYONEtDlpdutISQudWJOG49nhoUjoSfYjy3hNOEC0azcaMw2eJyL0pUwMHkm8gkVbLeBi6r2ZgsftnGGkR/Bl3baaByvX+qYUxbQGy8ZTWB0oJPKAg2uLI0Y=
install:
- docker --version
script:
- echo "This is test branch"
after_success:
- echo "build number" ${TRAVIS_BUILD_NUMBER}
- echo "job number" ${TRAVIS_JOB_NUMBER}
- echo ${TRAVIS_BRANCH}
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
notifications:
  email:
    on_success: never
    on_failure: never
