os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - BRANCH = ${TRAVIS_BRANCH}
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: cFq6lFQE/CPNl8xYjmaA5pxd8JByCNw3ha7o3Lpe5LPFXTNHeIjZPFWCYXs7YOAOApBEByFusZuXBCcs+RzKEk1TdPlBm1K1IZMi81xRySIHHKJcRPbBuAne/3/7cxf4timvlQecFpm+hJECNwYmDajBdv4fZaymovKscpzJfwRWSACFeqOEcNszOLBjF6fqJNzg8KSIIWgnflHUsltLY0t10CX1Plb6sBCNFsJUtoJd7etV9MXNsQwvAiIAv6PVBVxc5V2fLwKvJslVoDfkw80tYDfS1xi5b18k1aV/B53V/2KuLmotHGGHIgau9BcVhZ5OzsBbaCJP1ph8ctru/dZgviKNMjoWI/DLtlAgkW6u7rYs78VAYh8EEv8azcMq/MsBAEb7MJkJIxv4328PDcgESyUzCNhT1HkmKSC82g70Hj5j4R498QFRO7LR2/JN66SYqxp1+a/dvn7pvGRc/jXI4jet98jzNZZZcVB9Vg8UQDu11CvebR2ZOYWDQstgn1fKY95SNFjQ+RNbAWyPnqe0lVmBDTAZzriOr35LqLzpx26c6svqynMV2c9H3rP7Myoc2Sdv9/4pZgPunPAY75bZuVUhqtKmWi3/qdfvKy27jQXdb750l5BebI3w6TJR75ObAuII/JqAjrD1/sL3H0v4AUilDS4vlXi5etPzw6A=
  - secure: ZFkV6V4vIcT8iihXjAzQUhgGP6XwtMD9OZSe3fnc+Bg5MqHBF8FeDIPT/Z98m3EJ5kd5kBjUDZ0zxfJ0A7kq8TVRQEq7vHtr1MFlCeig1g8DVHIxo3z028UJV3dRNITO6ebLyzeGI5tkGpXoJ/pmbjeSrct80CHqlB8rIHxMvjE3Cos0aIWlus/XnpNgT6mUoc0qffO6IUCVnlNYLp+z4Ptrgjdwc7FpZmROIT8Fnd1Yxgt2W+1oK5a197+OEUGSpladXWFPjI2CYxpA5qgs1c3FGw/hsw1O+vbf8ExnsEC2KEFahg8rFGJ/yXbziwIb8vh1OqOfsaV68nWEEjx7YHdFFYAuNE1fPVqCQUbj+E4G+q7K4bUbzEVqjiJ5QsTO7cCszuK3apPI/0bbFSQrCtRkr+lAUptB/LdA4xACM1Y5AlelaEqSkc2wNYZ6LhrnGZsagZ0QJZn6RWHMd0EudE1cYzE3+MPkSezomc+WtZcMQsD1IUMZNhjuadOoZu2LscRKuFEAwaN5rVPSM/6gtsZLyT3/64Zl16KX065MovUK0SJLsOwoLgvbxqEeDWI8SQ1zsckdqcqERLjxZFFtU/vMAnJa+FLuqneLThqMW26+7uKW86HM3dFrdOaoKKgOBxVdw1Qx6X6vXnG3obH3HnyXuofKO9jRWRc38DYvU3Q=
install:
- docker --version
script:
- echo "This is test branch"
after_success:
- echo "build number" ${TRAVIS_BUILD_NUMBER}
- echo "job number" ${TRAVIS_JOB_NUMBER}
- echo ${TRAVIS_BRANCH}
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
notifications:
  email:
    on_success: never
    on_failure: never
