os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - BRANCH = ${TRAVIS_BRANCH}
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: v3b2GX2UuYEltPNCGtt4CiGDg7F5MOepQa8E3kj64SsN/MBPgafEKkor+dVbj40aaQx8UlIvtz5zs4KKJyzn10y7JumIER6fRlgGSOkwtmOdZhWcwIGWpoWbLCHTdKvwNIJ6pKUs6Erxz7V+LFLSHpnJmL8uAMMgCoO09BAj7coHPYjbsGxoqT57MmfskYprC2JYgC48el2s2T9vnGf7TIoZFVdVxdy5Bc0hpYrpGpdHYiLJ5wM/jPMzNUlSdSSABXUABZb8IeGEJf8/4VWpJ8g+XWwQ5rxU4UlUnT1F2Yvmp0BlBs2yZxij0Q6p9bpjTE5scNfNJpJeZcEv1qYMPx2vf00qyVTKl0mOmUORCKp4hau6dR1J/6jqES/aH7T2J/Gng5WpE9sZYaIGxFC8hfFPlDqIx64C9fErBH65tJR8IT9fmHfXwmnN/jwVS8s+JHmDuCFfhH0ijQCCysWff+zE5DU+8F1NSjemgziJBRqcVd/B64ZgN6h1OiNN3ff/4ylNtosOts83dHMsvSNqLtlLmKYPq25NyCLPSmYOdb5IBETxGV5yWZ/kYQ7IzS/CkYNWQHkZwY0WO6nBlX1IRKYvC+YFMle6HSHoojAh62BARBwo2t5sBeVD0NI9dMI+fwQB9+n0Om/iPdOhfRTDRgPAD40BGTh1FodV87r5s6M=
  - secure: eape9nyDZpT1PVccBcR8fjlbxP7e8Udv+iPJ7wkEWB1ddSiVmyd+tdhaOxAKmPReZgxbFdK+R6tiaQVh/wjWMeE5//MLlyKKznrhthlWtWc4rdqjDYGMfP3WfNldv2xWydKEcqH9HhgR+Ok8dgXpasOGLXEQrfs/Wa3BdVRM1/aBL98uy4iAxknZDEziXElzmrDnhBQcSBhaeM8xk2KASqtPJKXSXh3y0s7ILD/1LRUzLXfzaxtk/YWn97+m3RKFzu3atyJip28kKfh+nLDBwF70JiOXqGVNj14wqk2wSxnxRCeVlb5jO07QKy7+XviKlNsolcnO2lj7ZuL2VX+34z6UsqUWjQeeAbTh5XVNPpi6p8y0gDINBFuAYh3m9l4rcj+3SYOx69l3aHnJLLqZM0lDFkPZpTYIFvyWNzayIp5OHnf0JOHpH/n5Za0NHPiaelfB7Ofx/vwWRgO5YUOKNde/bkScpMW1OPXDD5Y+tguA/KhNtyz+iWJbvHAUT/HYi52PN1vZmZ1HlsE2eWlcRtYUsUaWvLwbKPBeehn6YTa2bjQSkFd3XGW+COcbNKArL20HmP4ka7/Vp13lMPssg9UrxZu99PJZmpfJ6/wq7pgp2JJIJE2kXoNks9MP2nne0/IN1FToHz79n9zLnPvdQIMR2qMGmXBlYxS/X4BFxSk=
install:
- docker --version
script:
- echo "This is test branch"
after_success:
- echo "build number" ${TRAVIS_BUILD_NUMBER}
- echo "job number" ${TRAVIS_JOB_NUMBER}
- echo ${TRAVIS_BRANCH}
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
notifications:
  email:
    on_success: never
    on_failure: never
