os: linux
# Travis CI template for cfsd

language: cpp

sudo: required

branches:
  only:
  - "/^master$/"
  - "/^test$/"

services:
- docker

addons:
  apt:
    update: false

env:
  global:
  - BRANCH = ${TRAVIS_BRANCH}
  - NUM = ${TRAVIS_BUILD_NUMBER}
  # - DOCKERHUB='chalmersfsd'
  # shell syntax #*/ means remove the first slash and string before it, for example, "cfsd/opendlv" would become "opendlv"
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`

install:
- docker --version

script:
#- docker build -f Dockerfile.amd64 -t ${IMAGE}:${BRANCH} .
- echo "This is test branch"

after_success:
- echo "build number" ${TRAVIS_BUILD_NUMBER}
- echo "job number" ${TRAVIS_JOB_NUMBER}
- echo ${NUM}
# - docker tag ${IMAGE}:${BRANCH} ${DOCKERHUB}/${IMAGE}:${TAG}
# - docker push ${DOCKERHUB}/${IMAGE}:${TAG}
# - echo "${DOCKERHUB}/${IMAGE}:${TAG}"

before_deploy:
- if [[ "${BRANCH}" == "test" ]]; then echo "test, no deploy"; exit 0; fi
# - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  
deploy:
  provider: script
  script: echo "this master branch"
  on:
    tag: false
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never
